#!/bin/sh

expected_platform="i386"
platform=`uname -p`
if [ ${platform} != ${expected_platform} ]; then
        echo "This package must be installed on ${expected_platform}"
        exit 1
fi
exit 0
